### ISSUE TITLE
I can't run mlgtools container

### ISSUE THREAD

**Issue by uebmaster** [Metaphorme/AutoDock-Vina-Docker#1]
Hi.

I've followed the instructions to run mlgtools container but when i execute:

docker run --rm -it -v $PWD:/data -v /tmp/.X11-unix:/tmp/.X11-unix ghcr.io/metaphorme/mgltools

I got:

```
setting PYTHONHOME environment
Run ADT from  /opt/mgltools/MGLToolsPckgs/AutoDockTools
Traceback (most recent call last):
  File "/opt/mgltools/MGLToolsPckgs/AutoDockTools/__init__.py", line 417, in runADT
    root = Tk()
  File "/opt/mgltools/lib/python2.7/lib-tk/Tkinter.py", line 1685, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: couldn't connect to display "host.docker.internal:0"
hit enter to continue
```

I've tried too with the next docker-compose file:

```
version: '3.3'
services:
    metaphorme:
        ports:
            - '80:80'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - '$PWD:/data'
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        restart: always
        logging:
            options:
                max-size: 1g
        image: ghcr.io/metaphorme/mgltools
```

But i got:

```
mlgtools-metaphorme-1  | Run ADT from  /opt/mgltools/MGLToolsPckgs/AutoDockTools
mlgtools-metaphorme-1  |     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
mlgtools-metaphorme-1  | TclError: couldn't connect to display "host.docker.internal:0"
mlgtools-metaphorme-1  | Traceback (most recent call last):
mlgtools-metaphorme-1  |   File "/opt/mgltools/MGLToolsPckgs/AutoDockTools/bin/runAdt.py", line 16, in <module>
mlgtools-metaphorme-1  |     AutoDockTools.runADT(sys.argv, ownInterpreter=ownInterpreter, AdtScriptPath=__file__)
mlgtools-metaphorme-1  |   File "/opt/mgltools/MGLToolsPckgs/AutoDockTools/__init__.py", line 574, in runADT
mlgtools-metaphorme-1  |     raw_input("hit enter to continue")
mlgtools-metaphorme-1  | EOFError: EOF when reading a line
mlgtools-metaphorme-1 exited with code 1
```

What am i doing wrong?

Thanks in advance.
